config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  use_doorkeeper

  # authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  delete 'files/:id/purge', to: 'files#purge', as: 'purge_file'

  post 'users/set_email', to: 'users#set_email', as: 'set_email'

  get 'search', to: 'search#index', as: 'search'

  concern :votable do
    member do
      post :vote
    end
  end

  concern :commentable do
    member do
      post :add_comment
    end
  end

  resources :rewards, only: :index

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true, only: %i[create update destroy] do
      post :mark_the_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show update create destroy], shallow: true do
        resources :answers, only: %i[index show update create destroy], shallow: true
      end
    end
  end

  resource :subscription, only: %i[create destroy]

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include LinkConcern
  include VoteConcern
  include CommentConcern

  belongs_to :user

  has_many :subscriptions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_one :reward, dependent: :destroy
  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :subscribe_author

  def subscribe_author
    user.subscriptions.create(question: self)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: %i[show update destroy]

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner

    if @question.save
      render json: @question
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    authorize @question

    if @question.update(question_params)
      render json: @question
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @question

    @question.destroy
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question
    @question ||= Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[index show]

  before_action :set_question, only: %i[show edit update destroy]
  before_action :gon_question_id, only: :show
  before_action :gon_question_user_id, only: :show
  after_action :publish_question, only: :create

  def index
    @questions = Question.all
  end

  def show
    @answers = @question.answers
    @answer = Answer.new
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.reward = Reward.new
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    authorize(@question)
    @question.update(question_params)
  end

  def destroy
    authorize(@question)

    @question.destroy

    redirect_to questions_path
  end

  private

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def gon_question_id
    gon.question_id = @question.id
  end

  def gon_question_user_id
    gon.question_user_id = @question.user_id
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast 'questions', @question
  end

  def question_params
    params.require(:question).permit(:title, :body, :vote_action, files: [],
                                                                  links_attributes: %i[id name url _destroy], reward_attributes: %i[id title image _destroy])
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/questions/_question.html.slim
.subscription
  -if current_user&.subscriptions&.find_by(question: question)
    = link_to "Unsubscribe", subscription_path(question_id: question.id), method: :delete, remote: true, local: false
  -elsif current_user
    = link_to "Subscribe", subscription_path(question_id: question.id), method: :post, remote: true, local: false

h1
  = question.title
p
  = question.body
  - if policy(question).edit?
    = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    = link_to 'Delete', question, method: :delete, confirm: 'Are you sure?'
  .question-errors
    = render 'shared/errors', resource: question

    = form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
      = f.label :title, 'Your question'
      br
      = f.text_field :title
      br
      = f.label :body
      br
      = f.text_area :body
      br
      = f.submit 'Save'

      = link_to 'Delete question', question, method: :delete
.rating
  'Rating:
  = question.rating
- if policy(question).vote?
  .vote-container *{class: [vote_display(question)]}
    =link_to "↑", vote_question_path(vote_action: 'upvote', id: question.id), method: :post, remote: true
    br
    =link_to "↓", vote_question_path(vote_action: 'downvote', id: question.id), method: :post, remote: true
  .unvote-container *{class: [unvote_display(question)]}
    =link_to "Unvote", vote_question_path(vote_action: 'unvote', id: question.id), method: :post, remote: true

.comments
  b Comments:
  = render question.comments

.comments-form
  -if signed_in?
    = render 'comments/form', commentable: question

app/views/questions/_reward_fields.html.slim
.nested-fields
  .field
    = f.label :title, 'Name'
    br
    = f.text_field :title
  .field
    = f.label :image
    br
    = f.file_field :image, accept: 'image/*'

app/views/questions/add_comment.js.erb
<% if @comment.persisted? %>
$('.question .comments').append('<%= j render @comment %>');
$('.question .comments-form #body').val('');
<% end %>

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  h1
    | Question's list
  .questions-list
    - @questions.each do |q|
      p
        = link_to q.title, q
  p
    = link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question
= form_with model: @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true
  p Links:
  p
    = f.fields_for :links do |link|
      = render "link_fields", f: link
    .links
      = link_to_add_association 'add link', f, :links
  = f.submit 'Ask'

  p Reward:
  p
    = f.fields_for :reward do |r|
      = render 'reward_fields', f: r

app/views/questions/show.html.slim
- cache @question do
  .question[id="question-#{@question.id}"]
    = render @question
  div
    - if @question.files.attached?
      - @question.files.each do |file|
        p.file-container id="file-id-#{file.id}"
          = link_to file.filename.to_s, url_for(file)
          - if policy(@question).destroy?
            = link_to 'delete file', purge_file_path(file), method: :delete, remote: true, class: 'delete-file-link'
  .links
    p Links:
    ul
      - @question.links.sort_by { |a| a.is_gist? ? 1 : 0 }.each do |link|
        - if link.is_gist?
          code data-gist-id="#{link.gist_id}"
        - else
          li= link_to link.name, link.url

.answer-errors
= form_with model: [@question, @answer], local: false, class: 'new-answer' do |f|
  = f.label :body, 'Your answer'
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true
  p Links:
  #links
    = f.fields_for :links do |link|
      = render "link_fields", f: link
    .links
      = link_to_add_association 'add link', f, :links
  = f.submit 'Answer'
.answers
  = render @answers

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
$('.question').html('<%= j render @question %>');
<% end %>