config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  use_doorkeeper

  # authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  delete 'files/:id/purge', to: 'files#purge', as: 'purge_file'

  post 'users/set_email', to: 'users#set_email', as: 'set_email'

  get 'search', to: 'search#index', as: 'search'

  concern :votable do
    member do
      post :vote
    end
  end

  concern :commentable do
    member do
      post :add_comment
    end
  end

  resources :rewards, only: :index

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true, only: %i[create update destroy] do
      post :mark_the_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show update create destroy], shallow: true do
        resources :answers, only: %i[index show update create destroy], shallow: true
      end
    end
  end

  resource :subscription, only: %i[create destroy]

  mount ActionCable.server => '/cable'
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    @search_query = params[:query]
    @filters = params[:filters].try(:[], :filter)&.reject(&:empty?)

    @result = ThinkingSphinx.search @search_query, classes: @filters&.map(&:constantize)
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
  def commentable_source_link(resource)
    if resource.commentable.instance_of?(Question)
      link_to resource.body, resource.commentable
    else
      link_to resource.body, resource.commentable.question
    end
  end
end

app/views/search/_answer.html.slim
div
  h2
    | Answer: &nbsp
    = link_to resource.question.title, question_path(resource.question)
  p
    | Body: &nbsp
    = resource.body
  p
    | Author: &nbsp
    = resource.user.email
hr

app/views/search/_comment.html.slim
div
  h2
    | Comment:&nbsp
    = commentable_source_link(resource)
  p
    | Author: &nbsp
    = resource.user.email
hr

app/views/search/_question.html.slim
div
  h2
    | Question: &nbsp
    = link_to resource.title, question_path(resource)
  p
    | Body: &nbsp
    = resource.body
  p
    | Author: &nbsp
    = resource.user.email
hr

app/views/search/_search.html.slim
= form_tag search_path, method: :get do
  = text_field_tag :query, params[:query]
  = collection_check_boxes :filters, :filter, %w[Question Answer User Comment], :to_s, :to_s
  = submit_tag 'Search'

app/views/search/_user.html.slim
div
  p
    | User: &nbsp
    = resource.email
hr

app/views/search/index.html.slim
- if !@result.empty?
  .search_results
    - @result.each do |resource|
      = render "search/#{resource.class.name.downcase}", resource: resource
- else
  p Nothing found