config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  use_doorkeeper

  # authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  delete 'files/:id/purge', to: 'files#purge', as: 'purge_file'

  post 'users/set_email', to: 'users#set_email', as: 'set_email'

  get 'search', to: 'search#index', as: 'search'

  concern :votable do
    member do
      post :vote
    end
  end

  concern :commentable do
    member do
      post :add_comment
    end
  end

  resources :rewards, only: :index

  resources :questions, concerns: %i[votable commentable], shallow: true do
    resources :answers, concerns: %i[votable commentable], shallow: true, only: %i[create update destroy] do
      post :mark_the_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show update create destroy], shallow: true do
        resources :answers, only: %i[index show update create destroy], shallow: true
      end
    end
  end

  resource :subscription, only: %i[create destroy]

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include LinkConcern
  include VoteConcern
  include CommentConcern

  belongs_to :question, touch: true
  belongs_to :user

  has_many_attached :files
  validates :body, presence: true

  scope :sort_by_best, -> { order(best: :desc) }

  def mark_the_best
    transaction do
      self.class.where(question_id:).update_all(best: false)
      update(best: true)
    end
  end

  after_commit :notify, on: %i[create update]

  def notify
    NotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!

  before_action :set_answer, only: %i[update destroy mark_the_best]
  after_action :publish_answer, only: :create

  def create
    @answer = Answer.new(answer_params)
    @answer.question = question
    @answer.user_id = current_user.id
    @answer.save
  end

  def update
    @answers = @answer.question.answers
    @answer.update(answer_params)
  end

  def destroy
    @answers = @answer.question.answers
    @answer.destroy
  end

  def mark_the_best
    @answer.mark_the_best
    return unless @answer.question.reward

    @answer.question.reward.user = @answer.user
    @answer.question.reward.save
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast "question_#{@answer.question.id}_answers", @answer
  end

  def answer_params
    params.require(:answer).permit(:body, :vote_action, files: [], links_attributes: %i[id name url _destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: %i[index create]
  before_action :set_answer, only: %i[show update destroy]

  def index
    @answers = @question.answers
    render json: @answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer
    else
      render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    authorize @answer

    if @answer.update(answer_params)
      render json: @answer
    else
      render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @answer

    @answer.destroy
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question
    @question ||= Question.find(params[:question_id])
  end

  def set_answer
    @answer ||= Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  li[id="answer-#{answer.id}"]
    - if policy(answer.question).edit? && answer.persisted? && !answer.best
      = link_to 'Best', mark_the_best_answer_path(answer), method: :post, remote: true
    - if answer.best
      'Best answer:
    = answer.body
    div
      - if answer.files.attached?
        - answer.files.each do |file|
          p.file-container id="file-id-#{file.id}"
            = link_to file.filename.to_s, url_for(file)
            - if policy(answer).destroy?
              = link_to 'delete file', purge_file_path(file), method: :delete, remote: true, class: 'delete-file-link'
      - answer.links.each do |link|
        p= link_to link.name, link.url
    .rating
      'Rating:
      = answer.rating
    - if policy(answer).vote?
      .vote-container *{class: [vote_display(answer)]}
        =link_to "↑", vote_answer_path(vote_action: 'upvote', id: answer.id), method: :post, remote: true
        br
        =link_to "↓", vote_answer_path(vote_action: 'downvote', id: answer.id), method: :post, remote: true
      .unvote-container *{class: [unvote_display(answer)]}
        =link_to "Unvote", vote_answer_path(vote_action: 'unvote', id: answer.id), method: :post, remote: true
    .comments
      b Comments:
      = render answer.comments

    .comments-form
      - if signed_in?
        = render 'comments/form', commentable: answer
  - if policy(answer).edit?
    p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    p= link_to 'Delete answer', answer_path(answer), method: :delete, remote: true

    = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      = f.label :body, 'Your answer'
      = f.text_area :body
      p
      = f.label :files
      = f.file_field :files, multiple: true
      = f.submit 'Save'

app/views/answers/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/answers/add_comment.js.erb
<% if @comment.persisted? %>
$("#answer-<%=@commentable.id%> .comments").append('<%= j render @comment %>');
$('.comments-form #body').val('');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% if @answer.persisted? %>
  $('.new-answer #answer_body').val('');
  $('.answers').append('<%= j render @answer %>');
<% end %>

app/views/answers/destroy.js.erb
$('.answers').html('<%= j render @answers %>');

app/views/answers/mark_the_best.js.erb
$('.answers').html('<%= j render @answer.question.answers.sort_by_best %>');

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% unless @answer.errors.present? %>
$('.answers').html('<%= j render @answers %>');
<% end %>